### PR TITLE
update biome temperature and rainfall

### PR DESCRIPTION
**Pull request by EtlamGit**
It seems that Minecraft changed the base values for temperature and rainfall for some Biomes. At the moment I don't know at what version this change occurred, but the changes here are made according to 1.10 (MCP931).
I also aligned the tabs for all lines. Therefore you have to use a better diff tool to see my modifications. There is much less changed than it looks here on GitHub.

### CODE REVIEW

**Comment by erich666** [comment]
Thanks for keeping this data up to date. Could you do me a favor and resubmit this PR, changing only the numbers you want to fix and not all the tabs and spaces? This would make it much easier for me and others to see exactly which biomes are affected.

**Comment by EtlamGit** [comment]
Yes, sure.
I had to align all lines vertically to be keep track of my changes versus the code lines from Minecraft. Do you see the lines vertically aligned at position of temperature and rainfall? If yes, what settings do you use?

I could imagine different ways to enhance this changeset in a new PullRequest:
 * first align tabs vertically, commit, change numbers, commit second time
 * try to get the numbers in the not aligned code, commit, align lines vertically, commit second time
 * try to get the numbers in the not aligned code, commit only once

You can choose. I can do the changes during night time when the (real) trees are chopped.

**Comment by erich666** [comment]
I set my IDE so that tabs represent 4 spaces, so everything aligns nicely for me. Well, there's actually a spot at the first Unknown Biome where the data shifts over 4 spaces to the right and continues that way - doesn't matter. I'm not changing this scheme, since it's used throughout the project's files, so please do just change the relevant numbers and leave the spacing alone. Or I can wade through and pick off the numbers myself and change them locally, but I worry that I'll miss one among all the whitespace changes.

**Comment by EtlamGit** [comment]
I changed my editor and did all the changes again for a new commit.
Most of the miss-alignment is caused by 1 TAB = 4 spaces by you, 8 spaces by GitHub and 2 spaces by my other editor.

**Comment by erich666** [comment]
OK, I folded it in manually to the mainstream; thanks.

**Pull request closed without merging**
